# Generated by Django 3.0.7 on 2020-08-17 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoatRecord',
            fields=[
                ('bid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('x', models.CharField(default='NULL', max_length=100)),
                ('y', models.CharField(default='NULL', max_length=100)),
                ('BoatTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RadoBoat',
            fields=[
                ('rid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bid', models.CharField(default='NULL', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SeaRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(default='NULL', max_length=100)),
                ('RankTime', models.DateTimeField(auto_now_add=True)),
                ('rid', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='common.RadoBoat')),
            ],
        ),
        migrations.CreateModel(
            name='RecognizeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seaInfo', models.TextField(default='NULL')),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('rid', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='common.RadoBoat')),
            ],
        ),
        migrations.CreateModel(
            name='RadoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radoData', models.ImageField(default='radoImages/default.jpg', upload_to='Images/%Y/%m/%d/')),
                ('UpdateTime', models.DateTimeField(auto_now_add=True)),
                ('rid', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='common.RadoBoat')),
            ],
        ),
    ]
