# Generated by Django 3.0.7 on 2020-09-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(default='NULL', max_length=100)),
                ('x', models.CharField(default='NULL', max_length=100)),
                ('y', models.CharField(default='NULL', max_length=100)),
                ('BoatTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BoatRecord',
        ),
    ]
