# Generated by Django 3.0.7 on 2020-09-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200908_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoatRecords',
            new_name='BoatRecord',
        ),
    ]
